# Site settings
title: SCVO Labs
description: We’re starting a participation revolution by doing good with new technologies.
url: "http://labs.scvo.org.uk"
permalink: /blog/:title/

# Account settings
twitter: scvolabs
facebook: 509241123
ganalytics: UA-3467930-8

# Build settings
markdown: kramdown
